# Docker Compose override for load testing environment
version: '3.8'

services:
  # Load testing service
  load-tester:
    build:
      context: ./scripts
      dockerfile: Dockerfile.loadtest
    depends_on:
      - frontend
      - backend
      - prometheus
    networks:
      - app-network
    environment:
      - TARGET_URL=http://backend:5000
      - FRONTEND_URL=http://frontend:3000
      - CONCURRENT_USERS=20
      - REQUESTS_PER_USER=100
    volumes:
      - ./load-test-reports:/app/load-test-reports
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 30 &&
        echo 'Starting load tests...' &&
        ./load-testing.sh &&
        echo 'Load testing completed!'
      "

  # Enhanced backend for load testing
  backend:
    environment:
      - NODE_ENV=production
      - ENABLE_METRICS=true
      - LOG_LEVEL=info
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Enhanced frontend for load testing  
  frontend:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  app-network:
    driver: bridge
