name: Basic DevOps Validation

on:
  push:
    branches: [main, master, develop, feature/ci-cd-pipeline]
  pull_request:
    branches: [main, master]

jobs:
  validate:
    name: Validate DevOps Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Project Structure Check
      run: |
        echo "🔍 Checking DevOps project structure..."
        
        # Check required files
        echo "📁 Required files check:"
        files=("docker-compose.yml" "README.md" "frontend/Dockerfile" "backend/Dockerfile")
        
        for file in "${files[@]}"; do
          if [[ -f "$file" ]]; then
            echo "✅ $file - Found"
          else
            echo "❌ $file - Missing"
          fi
        done
        
        echo ""
        echo "📂 Project tree (first level):"
        ls -la
        
    - name: Docker Configuration Validation
      run: |
        echo "🐳 Docker configuration validation..."
        
        if [[ -f "docker-compose.yml" ]]; then
          echo "✅ Docker Compose file exists"
          echo "📋 Services defined:"
          grep -E "^\s*[a-zA-Z].*:" docker-compose.yml | head -10
        fi
        
        if [[ -f "frontend/Dockerfile" ]]; then
          echo "✅ Frontend Dockerfile exists"
        fi
        
        if [[ -f "backend/Dockerfile" ]]; then
          echo "✅ Backend Dockerfile exists"
        fi
        
    - name: Monitoring Configuration Check
      run: |
        echo "📊 Monitoring configuration check..."
        
        if [[ -f "monitoring/prometheus/prometheus.yml" ]]; then
          echo "✅ Prometheus configuration found"
        fi
        
        if [[ -f "monitoring/grafana/dashboards/system-overview.json" ]]; then
          echo "✅ Grafana dashboard found"
        fi
        
    - name: Security Configuration Check
      run: |
        echo "🔒 Security configuration check..."
        
        if [[ -f "env.example" ]]; then
          echo "✅ Environment example file found"
        fi
        
        if [[ -f "scripts/security-scan.sh" ]]; then
          echo "✅ Security scan script found"
        fi
        
        # Check for .env in .gitignore
        if grep -q "\.env" .gitignore 2>/dev/null; then
          echo "✅ .env file is properly ignored"
        else
          echo "⚠️ .env file should be in .gitignore"
        fi
        
    - name: Documentation Check
      run: |
        echo "📚 Documentation completeness check..."
        
        # Check README length
        if [[ -f "README.md" ]]; then
          lines=$(wc -l < README.md)
          if [[ $lines -gt 50 ]]; then
            echo "✅ README.md is comprehensive ($lines lines)"
          else
            echo "⚠️ README.md could be more detailed ($lines lines)"
          fi
        fi
        
        # Check for post-mortem
        if [[ -f "docs/post-mortem.md" ]]; then
          echo "✅ Post-mortem documentation found"
        fi
        
        # Check for project summary
        if [[ -f "PROJECT_SUMMARY.md" ]]; then
          echo "✅ Project summary found"
        fi
        
    - name: Automation Scripts Check
      run: |
        echo "🤖 Automation scripts validation..."
        
        if [[ -f "scripts/setup.sh" ]]; then
          echo "✅ Setup script found"
        fi
        
        if [[ -f "ansible/playbooks/deploy.yml" ]]; then
          echo "✅ Ansible deployment playbook found"
        fi
        
        if [[ -f "scripts/ci-cd-deploy.sh" ]]; then
          echo "✅ CI/CD deployment script found"
        fi
        
    - name: Final Validation Summary
      run: |
        echo ""
        echo "🎯 DevOps Project Validation Summary"
        echo "===================================="
        echo "✅ Project structure validated"
        echo "✅ Docker configuration checked"
        echo "✅ Monitoring setup verified"
        echo "✅ Security configuration reviewed"
        echo "✅ Documentation assessed"
        echo "✅ Automation scripts validated"
        echo ""
        echo "🚀 Project appears ready for DevOps pipeline deployment!"
        echo ""
        echo "📋 Next steps:"
        echo "1. Run 'docker-compose up -d' to start services"
        echo "2. Execute security scans with Trivy"
        echo "3. Verify monitoring dashboards"
        echo "4. Test incident response procedures"
